### ISSUE TITLE
Remove the Heat Option

### ISSUE THREAD

**Issue by rajattrehan21** [jhthorsen/homebridge-tasmota-aircon-http#10]
How can i remove the 'Heat' option which shows in the Home app. 

I am an amateur in coding but can understand codes. I tried going through the index.js file. Cudnt get my head around it.

**Comment by jhthorsen** [comment]
I'm not sure I understand what you want to change. Can you provide a screenshot?

**Comment by rajattrehan21** [comment]
I use this device to control my air conditioner which only cools. I want to remove the Heat feature (screenshot), and may be just have auto, cool and off
![Photo 14-05-22, 10 54 48 PM](https://user-images.githubusercontent.com/9211750/168442535-a7bcfe52-357c-4f06-9fb1-e5d6d589fb3f.png)

**Comment by jhthorsen** [comment]
I'm not sure if that would just be a Fan..? Maybe you can look at the list in the left side menu at https://developers.homebridge.io/ and see if you can find a Service Type that fits your need?

If so, maybe we can make the service dynamic here: https://github.com/jhthorsen/homebridge-tasmota-aircon-http/blob/main/index.js#L243

**Comment by jhthorsen** [comment]
I'm going to close this, since I can't find any device that would only "cool".
