### ISSUE TITLE
Fan speed : auto

### ISSUE THREAD

**Issue by macjl** [jhthorsen/homebridge-tasmota-aircon-http#3]
Hello,

Many AC have the option to set the fan speed to « auto ». Tasmota irhvac command supports it too. Maybe this plugin should support ?

I think there could be an option in configuration to enable the « auto fan speed ». That will set this speed when the HomeKit fan speed slider would be set to a low level (or high if you prefers).
An other option could be to force the auto speed, whatever the slider level. 

What do you think about it ? If you like the idea, I could give a try to implement it, and submit a PR.

**Comment by jhthorsen** [comment]
The code in #6 was a very good start, but the PR is just too get around I'm afraid. Please have a look at the review comments - Looking forward to a new PR!
