### ISSUE TITLE
Get current temperature from Tasmota device

### ISSUE THREAD

**Issue by macjl** [jhthorsen/homebridge-tasmota-aircon-http#5]
Hello,

I have seen that the current temperatures of the AC device in HomeKit is set to the target temperature. In HomeKit best practices, this should be the real temperature of the room. I understand that the Tasmota device may not have a temperature sensor, so that’s why you did this. 

But for those who would add a temperature sensor to Tasmota (like I did), the plugin could discover it, and provides this temperature instead.

Do you think it would be a good improvement for this plugin ?

**Comment by jhthorsen** [comment]
I think this is awesome! Can you also update the documentation with some links to the hardware you used and/or tutorials on how to hook it up? I hope I can add this to my device 😄

**Comment by jhthorsen** [comment]
I'm going to close this issue, since I'm confident #9 will get merged. Thank you!
